
service: album-upload

custom:
  s3Bucket: jasny-test-public
  facebookAppId: 346280555872882 #Test Fiestainfo app (Fiestainfo LocalTest) - 346280555872882. Production app - 183989351617387

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: eu-west-1
  memorySize: 128
  timeout: 60
  deploymentBucket: fiestainfo-album-upload-lambda-deploy

  environment:
    FACEBOOK_APP_ID: ${self:custom.facebookAppId}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        'Fn::Join':
          - ''
          - ['arn:aws:s3:::', '${self:custom.s3Bucket}', '/*']

package:
  exclude:
    - '**'
  include:
    - handler.js
    - lambdas/**
    - package.json
    - node_modules/**
    - '!node_modules/aws-sdk/**'

functions:
  albumUpload:
    handler: handler.albumUpload
    events:
      - s3:
        bucket: ${self:custom.s3Bucket}
        event: s3:ObjectCreated:*
        rules:
          - suffix: .jpg 
